Traceback (most recent call last):
  File "C:\Users\User\anaconda3\lib\site-packages\jupyter_cache\executors\utils.py", line 51, in single_nb_execution
    executenb(
  File "C:\Users\User\anaconda3\lib\site-packages\nbclient\client.py", line 1204, in execute
    return NotebookClient(nb=nb, resources=resources, km=km, **kwargs).execute()
  File "C:\Users\User\anaconda3\lib\site-packages\nbclient\util.py", line 84, in wrapped
    return just_run(coro(*args, **kwargs))
  File "C:\Users\User\anaconda3\lib\site-packages\nbclient\util.py", line 62, in just_run
    return loop.run_until_complete(coro)
  File "C:\Users\User\anaconda3\lib\asyncio\base_events.py", line 616, in run_until_complete
    return future.result()
  File "C:\Users\User\anaconda3\lib\site-packages\nbclient\client.py", line 663, in async_execute
    await self.async_execute_cell(
  File "C:\Users\User\anaconda3\lib\site-packages\nbclient\client.py", line 965, in async_execute_cell
    await self._check_raise_for_error(cell, cell_index, exec_reply)
  File "C:\Users\User\anaconda3\lib\site-packages\nbclient\client.py", line 862, in _check_raise_for_error
    raise CellExecutionError.from_cell_and_msg(cell, exec_reply_content)
nbclient.exceptions.CellExecutionError: An error occurred while executing the following cell:
------------------
# convert raw numpy to mne
n_channels = data['EEG'].shape[0]+1
ch_types = ['eeg'] * n_channels
ch_types[-1] = 'stim'
ch_nms = ['Fz', 'Cz', 'Pz', 'CP1', 'CP3', 'C3', 'C4','status']
srate = 2048

info = mne.create_info(ch_names=ch_nms, sfreq=srate, ch_types=ch_types)

------------------

[1;31m---------------------------------------------------------------------------[0m
[1;31mNameError[0m                                 Traceback (most recent call last)
Input [1;32mIn [6][0m, in [0;36m<cell line: 8>[1;34m()[0m
[0;32m      5[0m ch_nms [38;5;241m=[39m [[38;5;124m'[39m[38;5;124mFz[39m[38;5;124m'[39m, [38;5;124m'[39m[38;5;124mCz[39m[38;5;124m'[39m, [38;5;124m'[39m[38;5;124mPz[39m[38;5;124m'[39m, [38;5;124m'[39m[38;5;124mCP1[39m[38;5;124m'[39m, [38;5;124m'[39m[38;5;124mCP3[39m[38;5;124m'[39m, [38;5;124m'[39m[38;5;124mC3[39m[38;5;124m'[39m, [38;5;124m'[39m[38;5;124mC4[39m[38;5;124m'[39m,[38;5;124m'[39m[38;5;124mstatus[39m[38;5;124m'[39m]
[0;32m      6[0m srate [38;5;241m=[39m [38;5;241m2048[39m
[1;32m----> 8[0m info [38;5;241m=[39m [43mmne[49m[38;5;241m.[39mcreate_info(ch_names[38;5;241m=[39mch_nms, sfreq[38;5;241m=[39msrate, ch_types[38;5;241m=[39mch_types)

[1;31mNameError[0m: name 'mne' is not defined
NameError: name 'mne' is not defined

